const annualdata = {
    bedding:  [ 
        {
        id: 1,
        name: "Geranium",
        scientificName: "Pelargonium",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/geranium.jpg",
        description: "Geraniums are vibrant, low-maintenance flowering plants that can thrive in New Mexico’s climate with the right care. They prefer moderate watering and well-drained soil, making them a good fit for Albuquerque’s dry conditions when protected from prolonged drought. Geraniums flourish in full to partial sun but appreciate some afternoon shade to shield their blooms from the intense summer heat. Deadheading spent flowers encourages continuous blooming, while occasional pruning helps maintain a tidy, compact form. These colorful plants are excellent for containers, garden beds, or borders, adding long-lasting seasonal color throughout the warmer months.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '5-9',
        matureSize: "3' x 3'",
        },
     
        {
        id: 3,
        name: "Petuna",
        scientificName: "Petunia × atkinsiana",
        image: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/57/Petunia_Violet.jpg/1024px-Petunia_Violet.jpg",
        description: "Petunias are colorful, fast-growing annuals that do well in New Mexico’s sunny, dry climate with regular care. They thrive in full sun but benefit from afternoon shade during Albuquerque’s peak summer heat. Petunias need consistent watering and well-drained soil, especially in containers. Deadheading encourages more blooms, and their spreading habit makes them ideal for borders, beds, and hanging baskets.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '5-9',
        matureSize: "3' x 3'",
        },
        {
            id: 2,
            name: "Marigold",
            scientificName: "Tagetes erecta",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/marigold.jpg",
            description: "Marigolds are hardy, sun-loving annuals that grow well in New Mexico’s dry, warm climate. They thrive in full sun and prefer well-drained soil, requiring only moderate watering once established, making them ideal for Albuquerque gardens. Their natural heat tolerance allows them to bloom consistently through the summer, though a bit of afternoon shade can help extend flowering during extreme heat. Regular deadheading promotes more blooms, and their compact, bushy growth makes them perfect for borders, containers, or companion planting. Marigolds also help repel common garden pests, adding both beauty and function to any landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
            waterRequirement: "Medium Water",
            hardinessZones: '5-9',
            matureSize: "3' x 3'",
            },
        {
        id: 3,
        name: "Cosmos",
        scientificName: "Cosmos bipinnatus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/cosmos.jpg",
        description: "Cosmos are tall, airy annuals that thrive in New Mexico’s hot, dry climate with minimal care. They prefer full sun and well-drained soil, and once established, they’re highly drought-tolerant—ideal for Albuquerque gardens. These low-maintenance flowers bloom profusely with occasional deadheading and do best when not overwatered or over-fertilized. Their feathery foliage and bright, daisy-like blooms make them great for borders, wildflower gardens, or pollinator-friendly spaces.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '5-9',
        matureSize: "3' x 3'",
        },
        {
        id: 3,
        name: "Snapdragon",
        scientificName: "Antirrhinum majus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/snapdragon.jpg",
        description: "Snapdragons are cool-season annuals that grow well in New Mexico, especially during spring and fall. They prefer full to partial sun and well-drained soil, with regular watering to keep them blooming. In Albuquerque’s climate, they benefit from some afternoon shade as temperatures rise. Deadheading encourages longer blooming, and their upright form and bright colors make them ideal for borders, garden beds, and cut flower arrangements.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '5-9',
        matureSize: "3' x 3'",
        },
 
    
        {
        id: 3,
        name: "Calibrachoa",
        scientificName: "Calibrachoa x hybrida",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/calibrachoa.jpg",
        description: "Calibrachoa, also known as million bells, are trailing annuals that thrive in New Mexico with the right care. They prefer full to partial sun and well-drained soil, and in Albuquerque’s hot summers, some afternoon shade helps protect their blooms. These plants need regular watering, especially in containers, but dislike soggy soil. With proper care and occasional deadheading, calibrachoa produce a nonstop display of small, petunia-like flowers, making them perfect for hanging baskets, window boxes, and cascading over garden edges.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '5-9',
        matureSize: "3' x 3'",
        },
        {
        id: 3,
        name: "Lobelia",
        scientificName: "Lobelia erinus",
        image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/lobelia.PNG",
        description: "Lobelia is a trailing annual that thrives in New Mexico’s cooler seasons, offering vibrant blue, purple, or white blooms. It prefers full sun to partial shade and well-drained soil, with regular watering to keep the soil evenly moist. In Albuquerque’s hot summer months, some afternoon shade can help protect it from the intense heat. Lobelia is perfect for hanging baskets, window boxes, or as a border plant, adding a splash of color and attracting pollinators like bees and butterflies.",
        sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
        sunRequirement: "Full Sun",
        waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
        waterRequirement: "Medium Water",
        hardinessZones: '5-9',
        matureSize: "3' x 3'",
        },

        {
            id: 2,
            name: "Verbena",
            scientificName: "Verbena x hybrida",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Verbena is a low-maintenance, heat-tolerant annual that thrives in New Mexico’s sunny climate. It prefers full sun and well-drained soil, requiring moderate watering once established. In Albuquerque’s summer heat, verbena flourishes with minimal care, blooming profusely with vibrant colors. Deadheading encourages continued flowering throughout the season. Its trailing habit makes it perfect for hanging baskets, containers, and borders, adding long-lasting color while attracting pollinators like bees and butterflies.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },


        {
            id: 2,
            name: "Nasturtium",
            scientificName: "Tropaeolum majus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Nasturtiums are vibrant, easy-to-grow annuals that thrive in New Mexico’s sunny, dry climate. They prefer full sun and well-drained soil, and once established, they are relatively drought-tolerant. Nasturtiums require moderate watering but do best when not overwatered. Their bright, edible flowers and round, peppery leaves make them a great addition to gardens, containers, or hanging baskets. They also attract pollinators like bees and butterflies and are perfect for adding color to borders or as ground cover.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
        {
            id: 2,
            name: "Dianthus",
            scientificName: "Dianthus caryophyllus",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Dianthus, also known as carnations or pinks, are hardy, fragrant annuals that thrive in New Mexico’s sunny climate. They prefer full sun and well-drained soil, with moderate watering once established. Dianthus is drought-tolerant and flourishes with minimal care, making it ideal for Albuquerque gardens. These flowers bloom in a variety of colors and are known for their clove-like fragrance. They’re perfect for borders, containers, or rock gardens, adding both color and a pleasant scent while attracting pollinators like bees and butterflies.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },

    ],

    droughttolerant: [
        {
            id: 2,
            name: "Gazania",
            scientificName: "Gazania rigens",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Gazanias are drought-tolerant, sun-loving annuals that thrive in New Mexico’s dry, hot climate. They prefer full sun and well-drained soil, requiring minimal watering once established. Gazanias bloom profusely with vibrant, daisy-like flowers in a range of colors, adding a bold pop to gardens and landscapes. In Albuquerque’s intense summer heat, they perform best with consistent sunlight and some protection from extreme afternoon heat. These low-maintenance flowers are perfect for borders, rock gardens, or containers, and they attract pollinators while providing long-lasting color.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
          {
            id: 2,
            name: "Zinnia",
            scientificName: "Zinnia bidens",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Zinnias are vibrant, heat-loving annuals that thrive in New Mexico’s sunny, dry climate. They prefer full sun and well-drained soil, needing moderate watering once established. Zinnias are highly drought-tolerant and bloom profusely throughout the summer, making them ideal for Albuquerque gardens. Regular deadheading encourages continuous flowering, and their bright, colorful blooms attract pollinators. Perfect for borders, containers, and cut flower gardens, zinnias add bold color and a cheerful touch to any landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
   
        {
            id: 11,
            name: "California Poppy",
            scientificName: "Eschscholzia californica",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/california-poppy.jpg",
            description: "California Poppy is a bright, cheerful annual that thrives in New Mexico’s dry, sunny climate. Known for its vibrant orange, yellow, or red flowers, it blooms from spring to early summer, adding a splash of color to gardens. This drought-tolerant plant prefers well-draining soil and full sun, making it ideal for xeriscaping or wildflower meadows. California Poppy requires minimal water once established and attracts pollinators like bees and butterflies, making it a great choice for low-maintenance, water-wise gardens.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "8-11",
            matureSize: `8" x 8"`,
            native: false
          },
    
            {
                id: 2,
                name: "Portulaca",
                scientificName: "Portulaca grandiflora",
                image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
                description: "Portulaca, or moss rose, is a heat-loving, drought-tolerant annual that thrives in New Mexico’s dry climate. With vibrant, rose-like blooms in shades of pink, red, orange, and yellow, it adds color to gardens from summer to fall. This low-growing succulent prefers full sun and well-draining soil, making it perfect for rock gardens, borders, or containers. Requiring little water, Portulaca is an excellent choice for xeriscaping and pollinator-friendly landscapes.",
                sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
                sunRequirement: "Full Sun",
                waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
                waterRequirement: "Low Water",
                hardinessZones: "10-11",
                matureSize: `6" x 12"`,
                native: false
              },
 
            {
                id: 2,
                name: "Celosia",
                scientificName: "Celosia argentea",
                image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
                description: "Celosia is a colorful, heat-loving annual that thrives in New Mexico’s sunny, dry climate. It prefers full sun and well-drained soil, requiring moderate watering once established. Celosia blooms in bright, feathery or spiky flowers in shades of red, pink, yellow, and orange, adding a bold splash of color to gardens. These drought-tolerant plants do well in Albuquerque’s intense heat and are perfect for borders, containers, or as cut flowers. Their striking texture and vibrant colors attract pollinators and make them a standout in any landscape.",
                sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
                sunRequirement: "Full Sun",
                waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
                waterRequirement: "Low Water",
                hardinessZones: "10-11",
                matureSize: `6" x 12"`,
                native: false
              },
              {
                id: 3,
                name: "Sunflower",
                scientificName: "Helianthus",
                image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/sunflower-1497092_1920.jpg",
                description: "Sunflowers are hardy, sun-loving annuals that flourish in New Mexico’s hot, dry climate. They thrive in full sun and well-drained soil, requiring moderate watering once established. In Albuquerque’s summer heat, they do best with consistent moisture but are relatively drought-tolerant. Sunflowers can grow tall, with vibrant yellow blooms that make a striking addition to gardens, fields, or as a backdrop for smaller plants. They’re perfect for attracting pollinators and adding a bold splash of color to any landscape.",
                sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
                sunRequirement: "Full Sun",
                waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
                waterRequirement: "Medium Water",
                hardinessZones: '5-9',
                matureSize: "3' x 3'",
                },
        
    ],

    shadetolerant: [
        {
            id: 2,
            name: "Alyssium",
            scientificName: "Lobularia maritima",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Alyssum is a low-growing, fragrant annual that thrives in New Mexico’s sunny, dry climate. It prefers full sun and well-drained soil, requiring moderate watering, especially during dry spells. Alyssum blooms in small, delicate clusters of white, pink, or purple flowers, creating a carpet of color that adds charm to any garden. It’s perfect for borders, containers, or ground cover, and its sweet fragrance attracts pollinators like bees and butterflies. Once established, Alyssum is drought-tolerant and low-maintenance, making it ideal for Albuquerque’s arid conditions.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
          {
            id: 3,
            name: "Impatiens",
            scientificName: "Impatiens walleriana",
            image: "https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Impatiens_walleriana_-_flower_view_02.jpg/1024px-Impatiens_walleriana_-_flower_view_02.jpg",
            description: "Impatiens are shade-loving annuals that can thrive in New Mexico with proper care and protection from intense sun. They prefer morning light and consistent moisture, making them well-suited for shady spots in Albuquerque gardens. Plant them in rich, well-drained soil and water regularly to keep the soil evenly moist. Their vibrant blooms and lush foliage make impatiens perfect for containers, shaded beds, and borders where other flowers may struggle.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
            waterRequirement: "Medium Water",
            hardinessZones: '5-9',
            matureSize: "3' x 3'",
            },
        {
            id: 2,
            name: "Begnoia",
            scientificName: "Begonia cucullata",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Begonias are shade-loving annuals that thrive in New Mexico’s cooler seasons, offering vibrant blooms in a variety of colors. They prefer partial to full shade and well-drained soil, with regular watering to keep the soil evenly moist. Begonias are ideal for Albuquerque’s hot summers, as they provide a burst of color in shaded areas. Their delicate flowers and attractive foliage make them perfect for containers, hanging baskets, and shaded garden beds, adding beauty and texture while being relatively low-maintenance.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
        {
            id: 2,
            name: "Coleus",
            scientificName: "Coleus scutellarioides",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Coleus is a vibrant, shade-loving annual that thrives in New Mexico’s warm climate with the right care. It prefers partial to full shade and well-drained soil, with regular watering to keep the soil evenly moist. Coleus offers a variety of colors and patterns in its foliage, ranging from deep reds to greens, purples, and yellows, making it an eye-catching addition to any garden. It’s perfect for containers, hanging baskets, or shaded garden beds, adding bold color and texture while being relatively low-maintenance and heat-tolerant.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
        {
            id: 2,
            name: "Caladium",
            scientificName: "Caladium bicolor",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Caladiums are striking, shade-loving perennials that thrive in New Mexico’s warmer months. They prefer partial to full shade and well-drained, moist soil, requiring regular watering to keep the soil consistently moist. Caladiums are known for their large, heart-shaped leaves in a variety of colors and patterns, including red, pink, white, and green, adding a bold, tropical touch to any garden. They’re ideal for containers, shaded beds, or as accent plants, providing vibrant color and texture while thriving in the cooler, shaded areas of Albuquerque’s landscape.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
   
        {
            id: 2,
            name: "Fuchsia",
            scientificName: "Fuchsia magellanica",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/Xeric/bedding/portulaca-2606950_1920.jpg",
            description: "Fuchsia is a vibrant, shade-loving annual that thrives in New Mexico’s cooler months, adding a pop of color to gardens. It prefers partial to full shade and well-drained, moist soil, requiring regular watering to keep the soil consistently moist. Fuchsia produces stunning, pendulous flowers in shades of pink, purple, red, and white, making it a striking addition to hanging baskets, containers, and shaded garden beds. Ideal for Albuquerque's hotter months, it provides a refreshing burst of color while attracting pollinators like hummingbirds and bees.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Low-water.png",
            waterRequirement: "Low Water",
            hardinessZones: "10-11",
            matureSize: `6" x 12"`,
            native: false
          },
          {
            id: 3,
            name: "Viola",
            scientificName: "Viola x wittrockiana",
            image: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/TypesofProducts/viola.PNG",
            description: "Wintergreen boxwood is a hardy, low-maintenance evergreen shrub that thrives in New Mexico with proper care. It prefers moderate water but is relatively drought-tolerant once established, making it suitable for Albuquerque’s dry climate. This shrub does best in partial to full sun but benefits from afternoon shade to protect against intense summer heat. Regular pruning maintains its shape, making it ideal for hedges, borders, or foundation plantings, while mulch helps retain moisture and regulate soil temperature.",
            sunIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/FullSun.png",
            sunRequirement: "Full Sun",
            waterIcon: "https://jericho-content.nyc3.cdn.digitaloceanspaces.com/VARIOUS/SEO_photos/plant_card_icons/Medium-water.png",
            waterRequirement: "Medium Water",
            hardinessZones: '5-9',
            matureSize: "3' x 3'",
            },
    ]
}

export default annualdata;
  